# Generated by Django 5.2 on 2025-05-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='homework_done',
            new_name='homework',
        ),
    ]
